feat: redeem for collection holder
coin98/coin98-vault-evm pull request #12
Opened 2024-06-05 08:43 UTC by c98tristan

- [x] Implement function
- [x] Unit test happy case
- [ ] Unit test cover

2024-06-05 09:03 UTC, imterryyy98 requested changes

2024-06-06 03:27 UTC, imduchuyyy requested changes

2024-06-06 03:27 UTC, imduchuyyy commented on contracts/MatrixVault.sol
> +    mapping(uint256 => mapping(uint256 => bool)) internal _isClaimed;
Rename to `isClaimedByNFT`

2024-06-06 03:27 UTC, imduchuyyy commented on contracts/MatrixVault.sol
> +        require(VRC725(collectionAddress).balanceOf(receiver) > 0, "C98Vault: Receiver has no NFT");
We can remove this check safely because we already have check for owner of TokenId should equal to receiver

2024-06-06 03:41 UTC, imterryyy98 requested changes

2024-06-06 03:41 UTC, imterryyy98 commented on contracts/MatrixVault.sol
> +    mapping(uint256 => mapping(uint256 => bool)) internal _isClaimed;
rename to `_isClaimedByToken`

2024-06-06 03:44 UTC, imterryyy98 commented
I suggest to split `redeemForCollectionHolder` into 2 functions, one function for specific tokenId, the other one for all tokenIds. You can implement internal functions to handle overlap validation logic and execution.

2024-06-12 03:27 UTC, imterryyy98 approved these changes
LGTM

2024-06-12 03:27 UTC, merged