Feature: Coin98VaultProxy for free gas user on Viction
coin98/coin98-vault-evm pull request #6
Opened 2024-01-29 10:15 UTC by c98tristan

2024-01-29 10:28 UTC, imterryyy requested changes

2024-01-29 10:28 UTC, imterryyy commented on contracts/Coin98VaultV2Proxy.sol
> +            IERC20(eventData.sendingToken).safeTransfer(vaultAddress, sendingAmount_);
Why you send token to vault ?

2024-01-29 10:28 UTC, imterryyy commented on contracts/Coin98VaultV2Proxy.sol
> +    struct EventData {
Please format code

2024-01-29 10:28 UTC, imterryyy commented on contracts/Coin98VaultV2Proxy.sol
> +            IERC20(eventData.sendingToken).safeTransferFrom(msg.sender, address(this), sendingAmount_);
please check `sendingToken != address(0)`

2024-01-29 10:28 UTC, imterryyy commented on contracts/Coin98VaultV2Proxy.sol
> +    mapping(uint256 => EventData) private _eventDatas;
What is this ?

2024-01-29 10:32 UTC, terryyyz-coin98 requested changes

2024-01-30 03:15 UTC, terryyyz-coin98 requested changes

2024-01-30 03:15 UTC, terryyyz-coin98 commented on tests/vault_sponsor_gas.spec.ts
> +    expect(balanceVaultAfter.sub(balanceVaultBefore).toNumber()).eq(1000);
use `changeTokensBalance` api to verify token transfer action.

2024-01-30 03:52 UTC, closed without merging