VaultNFT
coin98/coin98-vault-evm pull request #9
Opened 2024-05-08 09:53 UTC by c98tristan

2024-05-08 10:55 UTC, imterryyy98 requested changes

2024-05-08 10:55 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +    function mint(bytes32[] calldata proofs, address to, uint256 tokenId, uint256 _totalAlloc) external {
remove underscore before function parameters

2024-05-08 10:55 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +    function mint(bytes32[] calldata proofs, address to, uint256 tokenId, uint256 _totalAlloc) external {
re-order the params (address to, uint256 tokenId, uint256 totalAlloc, bytes32[] proofs)

2024-05-08 10:55 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +        WETH_ADDRESS = params.weth;
What this param using for? we don't have required about WETH

2024-05-08 10:55 UTC, imterryyy98 commented on contracts/Coin98VaultV2.sol
>  // SPDX-License-Identifier: Apache-2.0
Don't change this file

2024-05-08 19:08 UTC, c98tristan commented on contracts/Coin98VaultNFT.sol
> +    mapping(address => bool) private _adminStatuses;
Follow Coin98VaultV2 flow, _adminStatuses is used in modifier onlyAdmin

2024-05-09 04:52 UTC, c98tristan commented on contracts/Coin98VaultNFT.sol
> +        uint256 gasLimit = IVaultConfig(_factory).gasLimit();
Gas limit for sending Ether

2024-05-09 08:29 UTC, imterryyy98 requested changes

2024-05-09 08:29 UTC, imterryyy98 commented on contracts/Collection.sol
> +    function ownerOf(uint256 tokenId) public view virtual override(ICollection, IERC721, VRC725) returns (address) {
Why we need to override ownerOf function

2024-05-09 08:29 UTC, imterryyy98 commented on contracts/Collection.sol
> +    function claim(uint256 tokenId, uint256 claimedAmount) external nonReentrant {
Everyone can call this action and change data of `_claimedAlloc`

2024-05-09 08:29 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +        if (fee > 0) {
We can remove logic about fee.

2024-05-09 08:29 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +        if (_token == address(0)) {
Logic of transfer should be implement at the end of function.

2024-05-09 08:29 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +        uint256 gasLimit = IVaultConfig(_factory).gasLimit();
What does it mean, we can send Ether with the default gas limit.

2024-05-09 08:55 UTC, imterryyy98 requested changes

2024-05-09 08:55 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +        _vaultImplementation = implementation;
add event

2024-05-09 08:55 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +        _collectionImplementation = implementation;
add event

2024-05-09 08:55 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +    function getImplementation() public view returns (address) {
rename to getVaultImplementation

2024-05-09 08:55 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +    function getCollectionImplementationntation() public view returns (address) {
fix typo

2024-05-09 08:55 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +    modifier onlyAdmin() {
if you allow owner bypass this modifier, change the modifier name to `onlyOwnerOrAdmin`

2024-05-09 08:55 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +    bytes32 private merkleRoot;
underscore for private variable

2024-05-09 09:05 UTC, imterryyy98 requested changes

2024-05-09 09:05 UTC, imterryyy98 commented on package.json
> +    "@openzeppelin/contracts": "^4.9.6",
we can remove this package because we already clone the needed libraries in our repository.

2024-05-10 04:57 UTC, imterryyy98 requested changes

2024-05-10 04:57 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +    function getVaultAddress(bytes32 salt_) public view returns (address) {
Keep coding convention.

2024-05-10 04:57 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +    function getCollectionAddress(bytes32 salt_) public view returns (address) {
Keep coding convention.

2024-05-14 03:38 UTC, imterryyy98 requested changes

2024-05-14 03:38 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +    function createVaultWithCollection(
please keep code convention, underscore before name of internal function

2024-05-14 03:38 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +        Collection(collection).__Collection_init(params.name, params.symbol, address(this));
collection owner should be set to the user.

2024-05-14 03:43 UTC, imterryyy98 requested changes

2024-05-14 03:43 UTC, imterryyy98 commented on contracts/Coin98VaultNftProxy.sol
> +    constructor() VRC25("Coin98VaultNftProxy", "C98VNP", 18) {}
Let user input `name`, `symbol` for VRC25

2024-05-14 03:43 UTC, imterryyy98 commented on contracts/Coin98VaultNftProxy.sol
> +// SPDX-License-Identifier: Apache-2.0
Because all users can create their own vault, so I recommend add factory call functions to the proxy contract, help users can create their vault without worry about gas fee.

2024-05-14 03:43 UTC, imterryyy98 commented on contracts/Coin98VaultNftProxy.sol
> +        if (value > minFee()) {
return 0.

2024-05-14 03:47 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +        Collection(collection).__Collection_init(params.name, params.symbol, address(this));
If you worry that if the collection owner role was set to user, factory contract wouldn't able to add new minter address. I recommend that you can store factory address to the collection contract and allow factory to add new minter.

2024-05-14 10:24 UTC, imterryyy98 requested changes

2024-05-14 10:24 UTC, imterryyy98 commented on contracts/Collection.sol
> +    function __Collection_init(
use `msg.sender` as factory address

2024-05-14 10:24 UTC, imterryyy98 commented on contracts/Collection.sol
> +    modifier onlyOwnerAndFactory() {
`onlyOwnerOrFactory`

2024-05-14 10:24 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +    function vaults() external view returns (address[] memory) {
if `vaults` has too many addresses, this action will lead to memory leak error.

2024-05-15 04:08 UTC, imterryyy98 requested changes

2024-05-15 04:08 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +    function vaults(uint256 index) external view returns (address) {
change to `getVault`

2024-05-15 04:08 UTC, imterryyy98 commented on contracts/Coin98VaultNFTFactory.sol
> +    function collections(uint256 index) external view returns (address) {
change to `getCollection`

2024-05-15 04:15 UTC, imterryyy98 approved these changes

2024-05-27 02:22 UTC, tungng98 commented on contracts/Coin98VaultNFT.sol
> +            _schedules.push(params.schedules[i]);
validation is missing to ensure all schedules summed equal 100 percent

2024-05-27 02:23 UTC, tungng98 commented on contracts/Collection.sol
> +contract Collection is VRC725Enumerable, Initializable, ICollection, ReentrancyGuard {
this NFT is specifically designed for Vault, it should have specific name too

2024-05-27 02:27 UTC, tungng98 commented on contracts/Coin98VaultNFT.sol
> +    function setCollection(address collection) external onlyOwnerOrAdmin {
this function is redundant and dangerous, because collection is locked to one vault and must not be changed

2024-05-27 02:34 UTC, tungng98 commented on contracts/Coin98VaultNFT.sol
> +        _allocs[tokenId].totalAlloc = totalAlloc;
allocation will be stored in the collection instead, and won't be updated in any case

2024-05-27 03:47 UTC, c98tristan commented on contracts/Collection.sol
> +contract Collection is VRC725Enumerable, Initializable, ICollection, ReentrancyGuard {
Should we use VaultCollection or VaultNft for naming this contract?

2024-05-29 08:38 UTC, imterryyy98 requested changes

2024-05-29 08:38 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +    function split(address receiver, uint256 tokenId, uint256 rate) external payable nonReentrant {
Require caller must be owner of tokenId

2024-05-29 08:38 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +        require(rate > 0 && rate < 10000, "Coin98VaultNft: Invalid rate");
Add max Rate validation

2024-05-29 08:38 UTC, imterryyy98 commented on contracts/Coin98VaultNFT.sol
> +        if (_fee > 0) {
Support fee in USD and Token

2024-06-04 03:33 UTC, imterryyy98 commented
We can close this PR because implementation will be moved to https://github.com/coin98/coin98-vault-credit

2024-06-04 03:33 UTC, closed without merging